### PR TITLE
Adding support for request headers

### PR DESCRIPTION
**Pull request by dfulgham**
adding optional headers param to support custom headers, useful for proxy authentication etc. CouchDB 2.x

### CODE REVIEW

**Comment by mkeen** [comment]
@dfulgham I am happy to merge this, but can you remove any unnecessary formatting changes (quotes, linebreaks, etc), and also confirm you aren't adding any unnecessary imports? At first glance, there are a lot of new imports, and I just want to make sure they're needed. Looks good though, and I totally recognize the need for these request headers to be added. :+1:

**Comment by dfulgham** [comment]
@mkeen sorry about that I had prettier installed and it made those automatically.  Are you using anautoformatter on this project? if so which and I can update.

**Comment by mkeen** [comment]
@dfulgham Not using an autoformatter. Just doing it by hand for now. Will think about adding one to the project soon. See if you can match up the formatting from before by comparing the diffs for now if you don't mind. On second look, imports look good. Once formatting is tweaked, I will merge and republish to NPM.

**Comment by dfulgham** [comment]
@mkeen I will reformat to match.

**Comment by mkeen** [comment]
@dfulgham Closing. Headers support added in #3

**Pull request closed without merging**
